# Generated by Django 3.1.1 on 2020-09-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200906_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('surname', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(choices=[(0, 0), (6, 6), (12, 12), (15, 15), (18, 18)]),
        ),
    ]
